# Generated by Django 5.1.7 on 2025-03-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="cgpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
